friends = ["PK", "Shanky", "Jash","XX", "YY"]
print(friends)

print(friends[0])
print(friends[1])
print(friends[2])
print(friends[-1])
print(friends[-2])
print(friends[1:3])
print(friends[1:])
print(friends[:3])
friends.append("ZZ") #append at the end.
print(friends)
friends.remove("XX")
friends.insert(2, "PKInsert")
print(friends.index('PK'))
print(friends.pop())
friends.sort()
print(friends)
print(friends.count("PK"))
friends2 = friends.copy()
print(friends2)
friends2.reverse()
print(friends2)
