print("Giraffe Academy")
print("Giraffe\nAcademy")
phrase = "Giraffe Academy"
print(phrase.upper())
print(phrase.lower())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[-1])
print(phrase.index("G"))
print(phrase.index("f"))
print(phrase.index("A"))
print(phrase.replace("A", "a"))
print(phrase.replace("Giraffe", "Elephant"))
